[package]
name = "snx"
version = "0.0.5"
edition = "2024"
description = "an experimental batteries-included web framework"
authors = ["Julian Ollivieira"]
documentation = "https://docs.rs/snx"
repository = "https://github.com/snx-rs/snx"
license = "MIT"

[lib]
bench = false
path = "crates/snx/lib.rs"
name = "snx"

[workspace]
resolver = "3"
members = [
	"crates/app",
	"crates/macros",
	"crates/tokio",
	"crates/http",
]

[workspace.dependencies]
tracing = "0.1.44"
bytes = "1.12.1"
thiserror = "2.0.20"
jiff = "0.2.35"
futures = { version = "0.3.33", default-features = false, features = ["alloc", "std"] }
http_ext = { package = "http", version = "1.5.0" }

[features]
tokio = []

[dependencies]
app = { path = "crates/app" }
tokio = { path = "crates/tokio" }
http = { path = "crates/http" }
macros = { path = "crates/macros" }
